Add dry run publish steps

diff --git a/.github/workflows/bloc_presentation-test.yml b/.github/workflows/bloc_presentation-test.yml
--- a/.github/workflows/bloc_presentation-test.yml
+++ b/.github/workflows/bloc_presentation-test.yml
@@ -6,12 +6,12 @@ on:
     ignore-tags: ['bloc_presentation-v*']
     paths:
       - 'packages/bloc_presentation/**'
-      - ".github/workflows/bloc_presentation-test.yml"
+      - .github/workflows/bloc_presentation-test.yml
   pull_request:
     branches: [master]
     paths:
       - 'packages/bloc_presentation/**'
-      - ".github/workflows/bloc_presentation-test.yml"
+      - .github/workflows/bloc_presentation-test.yml
 
 jobs:
   test:
@@ -58,3 +58,7 @@ jobs:
 
       - name: Run tests
         run: flutter test
+
+      - name: Dry run pub publish
+        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
+        run: dart pub publish --dry-run || true
diff --git a/.github/workflows/bloc_presentation_test-test.yml b/.github/workflows/bloc_presentation_test-test.yml
--- a/.github/workflows/bloc_presentation_test-test.yml
+++ b/.github/workflows/bloc_presentation_test-test.yml
@@ -6,12 +6,12 @@ on:
     ignore-tags: ['bloc_presentation_test-v*']
     paths:
       - 'packages/bloc_presentation_test/**'
-      - ".github/workflows/bloc_presentation_test-test.yml"
+      - .github/workflows/bloc_presentation_test-test.yml
   pull_request:
     branches: [master]
     paths:
       - 'packages/bloc_presentation_test/**'
-      - ".github/workflows/bloc_presentation_test-test.yml"
+      - .github/workflows/bloc_presentation_test-test.yml
 
 jobs:
   test:
@@ -55,3 +55,7 @@ jobs:
 
       - name: Run analyzer
         run: flutter analyze --fatal-warnings --fatal-infos
+
+      - name: Dry run pub publish
+        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
+        run: dart pub publish --dry-run || true
